export const actionTypes = {
    USER_LOGIN_REQUEST : "USER_LOGIN_REQUEST",
    USER_LOGIN_ERROR : "USER_LOGIN_ERROR",
    USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",

    USER_REGISTER_REQUEST : "USER_REGISTER_REQUEST",
    USER_REGISTER_ERROR : "USER_REGISTER_ERROR",
    USER_REGISTER_SUCCESS : "USER_REGISTER_SUCCESS",

    USER_LOGOUT_REQUEST : "USER_LOGOUT_REQUEST",

    GET_TODO_REQUEST : "GET_TODO_REQUEST",
    GET_TODO_ERROR : "GET_TODO_ERROR",
    GET_TODO_SUCCESS : "GET_TODO_SUCCESS",

    POST_TODO_REQUEST : "POST_TODO_REQUEST",
    POST_TODO_ERROR : "POST_TODO_ERROR",
    POST_TODO_SUCCESS : "POST_TODO_SUCCESS",

    USER_DETAIL_REQUEST : "USER_DETAIL_REQUEST",
    USER_DETAIL_SUCCESS : "USER_DETAIL_SUCCESS",
    USER_DETAIL_ERROR : "USER_DETAIL_ERROR",

    MANIPULATE_TODO_LIST : "MANIPULATE_TODO_LIST",
}